live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"

[font]
size = 7.0

[env]
WINIT_X11_SCALE_FACTOR = "1.66"

[scrolling]
history = 1000

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "None"
dynamic_padding = true

