#! /bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &


# Monitors
xrandr --output DP-1 --mode 2560x1440 --above eDP-1
bspc monitor eDP-1 -d 4 5 6
bspc monitor DP-1 -d 1 2 3
bspc wm -O DP-1 eDP-1 

# Border config
bspc config focused_border_color "#ffff00"
bspc config border_width 1

bspc config window_gap           0
bspc config top_padding          0


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Launch polybar
$HOME/.config/polybar/polybar_launch.sh

#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP-1)

bspc rule -a Zathura state=tiled

# Wallpaper
feh --bg-fill ~/Pictures/Wallpapers/pexels-veeterzy-39811.jpg

# Touchpad speed
xinput set-prop 'Elan Touchpad' 'libinput Accel Speed' 1

# Keyboard layout
setxkbmap -option grp:win_space_toggle us,il
